name: PDF generation

on:
  push:
    branches: [ add-github-actions ]
  pull_request:
    branches: [ add-github-actions ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run start --if-present
    - run: npm run create-pdf2
